# Site settings
exclude: [README.md,example1.md,example2.md]
title: Nora Kassner
email: kassner . nora @ gmail . com
github: norakassner
twitter: KassnerNora
scholar_id: SGYr45MAAAAJ&hl
description: > # this symbol means ignore newlines until "baseurl:"
    Hi! I'm Nora.
baseurl: "" # keep blank unless you're using sub-paths
url: "http://norakassner.github.io" # the base hostname & protocol for your site
#paginate: 3

# you can also declare arbitrary key-value data here


# Build settings
markdown: kramdown
